#!/usr/bin/env ruby
require "dotenv/load"

rum :"rumrunner/ruby2.7" do
  tag Time.now.utc.strftime("%Y.%-m.%-d")

  env :TERRAFORM => "latest"

  stage :build
  stage :test => :build
  stage :plan => :test do
    build_arg :AWS_ACCESS_KEY_ID
    build_arg :AWS_SECRET_ACCESS_KEY
    build_arg :AWS_DEFAULT_REGION => "us-east-1"
  end

  artifact "Gemfile.lock" => :build
  artifact "package.zip"  => :build

  default %w[Gemfile.lock package.zip plan]
end
