#!/usr/bin/env ruby

cargo :"registry:5000/cargofile/example" do
  default ["pkg/vendor.zip", "Gemfile.lock"]

  # Base tag name for built images
  tag %x(git describe --tags --always).strip

  # Shared environment variable (--build-arg / --env)
  env :RUNTIME => "ruby2.5"

  # Build stages
  stage :build
  stage :test => :build
  stage :plan => :test do
    build_arg :AWS_ACCESS_KEY_ID
    build_arg :AWS_DEFAULT_REGION
    build_arg :AWS_SECRET_ACCESS_KEY
  end

  # Build artifacts
  artifact "Gemfile.lock" => :build
  artifact "pkg/vendor.zip" => :build do
    cmd %w[zip -r - vendor]
  end

  # Shell customizations
  shell :build do
    entrypoint "/bin/bash"
  end

  shell :plan do
    env :AWS_ACCESS_KEY_ID
    env :AWS_DEFAULT_REGION
    env :AWS_SECRET_ACCESS_KEY
  end
end
