#!/usr/bin/env ruby
gem = Gem::Specification::load "rumrunner.gemspec"
pkg = "pkg/#{gem.full_name}.gem"

rum "rumrunner:#{gem.version}" do
  env :RUBY_VERSION => ENV["RUBY_VERSION"] || "latest"

  stage :install
  stage :test => :install
  stage :build => :test

  artifact pkg => :build

  export "Gemfile.lock" => :install
end

desc "Push `#{pkg}` to rubygems.org"
task :push => pkg do
  sh "gem", "push", pkg
end

task default: %W[#{pkg} Gemfile.lock]
