#!/usr/bin/env ruby
gem = Gem::Specification::load "rumrunner.gemspec"
pkg = "pkg/#{gem.full_name}.gem"

rum :"rumrunner:#{gem.version}" do
  env :RUBY => ENV["RUBY"] || "latest"

  # docker build --build-arg RUBY=latest --iidfile {iidfile} --target install --tag rumrunner:{tag}-install .
  # docker build --build-arg RUBY=latest --iidfile {iidfile} --target test    --tag rumrunner:{tag}-test    .
  # docker build --build-arg RUBY=latest --iidfile {iidfile} --target build   --tag rumrunner:{tag}-build   .
  # docker build --build-arg RUBY=latest --iidfile {iidfile}                  --tag rumrunner:{tag}         .

  stage :install
  stage :test => :install
  stage :build => :test
  build :latest => :build

  export "Gemfile.lock" => :install

  artifact pkg => :build
end

task :default => %W[Gemfile.lock #{pkg}]

desc "Push `#{pkg}` to rubygems.org"
task(:push => pkg) { sh "gem push #{pkg}" }
