#!/usr/bin/env ruby
cargo :"cargofile/ruby2.5" do
  default ["Gemfile.lock", "lambda.zip"]

  tag Time.now.utc.strftime("%Y.%-m.%-d")

  stage :build
  stage :test
  stage :plan do
    build_arg :AWS_ACCESS_KEY_ID
    build_arg :AWS_SECRET_ACCESS_KEY
    build_arg :AWS_DEFAULT_REGION => "us-east-1"
  end

  artifact "Gemfile.lock" => :build
  artifact "lambda.zip"   => :build
end
