source "https://rubygems.org"

gem "activesupport", "~> 5.2", require: "active_support/all"

group :test do
  gem "rake", "~> 12.3"
end

group :development do
  gem "rumfile", "~> 0.1"
  gem "pry",     "~> 0.12"
end
