source "https://rubygems.org"

gem "activesupport", "~> 5.2", require: "active_support/all"

group :test do
  gem "rake", "~> 13.0"
end

group :development do
  gem "dotenv",    "~> 2.7"
  gem "rumrunner", "~> 0.5"
end
