#!/usr/bin/env ruby
rum :"rumrunner/ruby2.5" do
  tag Time.now.utc.strftime("%Y.%-m.%-d")

  env :TERRAFORM_VERSION => "0.12.5"

  stage :build
  stage :test
  stage :plan do
    build_arg :AWS_ACCESS_KEY_ID
    build_arg :AWS_SECRET_ACCESS_KEY
    build_arg :AWS_DEFAULT_REGION => "us-east-1"
  end

  artifact "Gemfile.lock" => :build
  artifact "lambda.zip"   => :build

  default ["Gemfile.lock", "lambda.zip"]
end
